---
- name: Version Control SSH Config
  blockinfile:
    path: "{{ home }}/.ssh/config"
    create: yes
    marker: "# {mark} {{ item.name | upper }} SSH CONFIG"
    block: |
      Host {{ item.url }}
        IdentityFile {{ home }}/.ssh/{{ item.name | lower }}
  loop: "{{ vc_tools }}"

- name: General SSH Config
  blockinfile:
    path: "{{ home }}/.ssh/config"
    create: yes
    insertafter: EOF
    marker: "# {mark} GENERAL SSH CONFIG"
    block: |
      Host *
        AddKeysToAgent yes
        UseKeychain yes
        IdentityFile {{ home }}/.ssh/id_rsa
