---
- name: Set general exports
  blockinfile:
    path: "{{ zshrc }}"
    create: yes
    marker: "# {mark} GENERAL EXPORTS"
    block: |
      export PATH=$PATH:$HOME/.tools
      export LC_ALL=en_US.UTF-8
      export PYTHONDONTWRITEBYTECODE=1 # Disables creation of .pyc and .pyo files
      export PIPENV_VENV_IN_PROJECT=1 # Creates pipenv virtualenvs under project directory
      export HOMEBREW_NO_AUTO_UPDATE=1 # Don't auto update homebrew at every execution
