---
- name: Get pinentry-mac location
  command: which pinentry-mac
  register: pinentry_mac

- name: GPG Agent Config
  blockinfile:
    path: "{{ home }}/.gnupg/gpg-agent.conf"
    create: yes
    marker: "# {mark} GPG AGENT CONFIG"
    block: |
      default-cache-ttl 0
      max-cache-ttl 1
      pinentry-program {{ pinentry_mac.stdout }}
      default-cache-ttl-ssh 0
      max-cache-ttl-ssh 0

- name: Disable option to save password
  command: defaults write org.gpgtools.common DisableKeychain -bool yes
