---
- name: Install oh-my-zsh
  block:
    - name: Check if oh-my-zsh is installed
      stat:
        path: "{{ home }}/.oh-my-zsh"
      register: omz

    - name: Download and run oh-my-zsh installer
      block:
        - get_url:
            url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
            dest: /tmp/install_oh_my_zsh.sh
            mode: u=rwx,g=rx,o=rx

        - script:
            cmd: /tmp/install_oh_my_zsh.sh --unattended
            executable: /bin/sh
      when: not omz.stat.exists
